###
POST http://localhost:3001/api/users
content-type: application/json

  {
    "username": "dan",
    "email": "someone@somewhere.com",
    "name": "dan",
    "password": "password"
  }

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
content-type: application/json

  {
    "username": "yoshi",
    "email": "someone@somewhere.com",
    "name": "yoshi",
    "password": "password"
  }
