GET http://localhost:3001/api
content-type: application/json


###
POST http://localhost:3001/api/items
content-type: application/json

{
"name" : "not a microwave",
"category": "kitchenware",
"description": "a micro",
"image":"a url",
"tippingDate": "2022-12-21T15:13:13.950Z"
}



###

GET http://localhost:3001/api/items

###

GET http://localhost:3001/api/items/63a081fa078260742e556f04

###

DELETE  http://localhost:3001/api/items/63a08202078260742e556f06

###

PATCH http://localhost:3001/api/items/63a081fa078260742e556f04


{"name": "microwave 2.0"}